export const WASM_COLLECTION_NFT_S_FETCH_IN_PROGRESS = 'WASM_COLLECTION_NFT_S_FETCH_IN_PROGRESS';
export const WASM_COLLECTION_NFT_S_FETCH_SUCCESS = 'WASM_COLLECTION_NFT_S_FETCH_SUCCESS';
export const WASM_COLLECTION_NFT_S_FETCH_ERROR = 'WASM_COLLECTION_NFT_S_FETCH_ERROR';

export const WASM_NFT_INFO_FETCH_IN_PROGRESS = 'WASM_NFT_INFO_FETCH_IN_PROGRESS';
export const WASM_NFT_INFO_FETCH_SUCCESS = 'WASM_NFT_INFO_FETCH_SUCCESS';
export const WASM_NFT_INFO_FETCH_ERROR = 'WASM_NFT_INFO_FETCH_ERROR';

export const WASM_COLLECTION_FETCH_IN_PROGRESS = 'WASM_COLLECTION_FETCH_IN_PROGRESS';
export const WASM_COLLECTION_FETCH_SUCCESS = 'WASM_COLLECTION_FETCH_SUCCESS';
export const WASM_COLLECTION_FETCH_ERROR = 'WASM_COLLECTION_FETCH_ERROR';

export const WASM_COLLECTION_HASH_FETCH_IN_PROGRESS = 'WASM_COLLECTION_HASH_FETCH_IN_PROGRESS';
export const WASM_COLLECTION_HASH_FETCH_SUCCESS = 'WASM_COLLECTION_HASH_FETCH_SUCCESS';
export const WASM_COLLECTION_HASH_FETCH_ERROR = 'WASM_COLLECTION_HASH_FETCH_ERROR';
