export const WASM_ALL_COLLECTIONS_FETCH_IN_PROGRESS = 'WASM_ALL_COLLECTIONS_FETCH_IN_PROGRESS';
export const WASM_ALL_COLLECTIONS_FETCH_SUCCESS = 'WASM_ALL_COLLECTIONS_FETCH_SUCCESS';
export const WASM_ALL_COLLECTIONS_FETCH_ERROR = 'WASM_ALL_COLLECTIONS_FETCH_ERROR';
