export const EMPTY_VALUES_SET = 'EMPTY_VALUES_SET';

export const ALLOWANCES_FETCH_IN_PROGRESS = 'ALLOWANCES_FETCH_IN_PROGRESS';
export const ALLOWANCES_FETCH_SUCCESS = 'ALLOWANCES_FETCH_SUCCESS';
export const ALLOWANCES_FETCH_ERROR = 'ALLOWANCES_FETCH_ERROR';
