export const COLLECTION_NFT_S_FETCH_IN_PROGRESS = 'COLLECTION_NFT_S_FETCH_IN_PROGRESS';
export const COLLECTION_NFT_S_FETCH_SUCCESS = 'COLLECTION_NFT_S_FETCH_SUCCESS';
export const COLLECTION_NFT_S_FETCH_ERROR = 'COLLECTION_NFT_S_FETCH_ERROR';

export const TRANSFER_DIALOG_SHOW = 'TRANSFER_DIALOG_SHOW';
export const TRANSFER_DIALOG_HIDE = 'TRANSFER_DIALOG_HIDE';
export const BURN_DIALOG_SHOW = 'BURN_DIALOG_SHOW';
export const BURN_DIALOG_HIDE = 'BURN_DIALOG_HIDE';

export const CHAIN_ID_SET = 'CHAIN_ID_SET';
export const TRANSFER_ADDRESS_SET = 'TRANSFER_ADDRESS_SET';
export const NFT_ID_SET = 'NFT_ID_SET';
