export const COLLECTIONS_FETCH_IN_PROGRESS = 'COLLECTIONS_FETCH_IN_PROGRESS';
export const COLLECTIONS_FETCH_SUCCESS = 'COLLECTIONS_FETCH_SUCCESS';
export const COLLECTIONS_FETCH_ERROR = 'COLLECTIONS_FETCH_ERROR';
