export const COLLECTION_NFT_S_FETCH_IN_PROGRESS = 'COLLECTION_NFT_S_FETCH_IN_PROGRESS';
export const COLLECTION_NFT_S_FETCH_SUCCESS = 'COLLECTION_NFT_S_FETCH_SUCCESS';
export const COLLECTION_NFT_S_FETCH_ERROR = 'COLLECTION_NFT_S_FETCH_ERROR';
