export const CONTRACTS_FETCH_IN_PROGRESS = 'CONTRACTS_FETCH_IN_PROGRESS';
export const CONTRACTS_FETCH_SUCCESS = 'CONTRACTS_FETCH_SUCCESS';
export const CONTRACTS_FETCH_ERROR = 'CONTRACTS_FETCH_ERROR';
