export const CHAIN_VALUE_SET = 'CHAIN_VALUE_SET';
export const TAB_VALUE_SET = 'TAB_VALUE_SET';

export const MARKETPLACE_NFT_S_FETCH_SUCCESS = 'MARKETPLACE_NFT_S_FETCH_SUCCESS';
export const MARKETPLACE_NFT_S_FETCH_IN_PROGRESS = 'MARKETPLACE_NFT_S_FETCH_IN_PROGRESS';
export const MARKETPLACE_NFT_S_FETCH_ERROR = 'MARKETPLACE_NFT_S_FETCH_ERROR';
