export const CONNECT_KEPLR_ACCOUNT_IN_PROGRESS = 'CONNECT_KEPLR_ACCOUNT_IN_PROGRESS';
export const CONNECT_KEPLR_ACCOUNT_SUCCESS = 'CONNECT_KEPLR_ACCOUNT_SUCCESS';
export const CONNECT_KEPLR_ACCOUNT_ERROR = 'CONNECT_KEPLR_ACCOUNT_ERROR';

export const KEPLR_ACCOUNT_KEYS_SET = 'KEPLR_ACCOUNT_KEYS_SET';

export const BALANCE_FETCH_IN_PROGRESS = 'BALANCE_FETCH_IN_PROGRESS';
export const BALANCE_FETCH_SUCCESS = 'BALANCE_FETCH_SUCCESS';
export const BALANCE_FETCH_ERROR = 'BALANCE_FETCH_ERROR';

export const PROTO_BUF_SIGN_IN_PROGRESS = 'PROTO_BUF_SIGN_IN_PROGRESS';
export const PROTO_BUF_SIGN_SUCCESS = 'PROTO_BUF_SIGN_SUCCESS';
export const PROTO_BUF_SIGN_ERROR = 'PROTO_BUF_SIGN_ERROR';

export const TX_SIGN_IN_PROGRESS = 'TX_SIGN_IN_PROGRESS';
export const TX_SIGN_SUCCESS = 'TX_SIGN_SUCCESS';
export const TX_SIGN_ERROR = 'TX_SIGN_ERROR';

export const TX_SIGN_AND_BROAD_CAST_IN_PROGRESS = 'TX_SIGN_AND_BROAD_CAST_IN_PROGRESS';
export const TX_SIGN_AND_BROAD_CAST_SUCCESS = 'TX_SIGN_AND_BROAD_CAST_SUCCESS';
export const TX_SIGN_AND_BROAD_CAST_ERROR = 'TX_SIGN_AND_BROAD_CAST_ERROR';

export const TX_HASH_FETCH_IN_PROGRESS = 'TX_HASH_FETCH_CAST_IN_PROGRESS';
export const TX_HASH_FETCH_SUCCESS = 'TX_HASH_FETCH_CAST_SUCCESS';
export const TX_HASH_FETCH_ERROR = 'TX_HASH_FETCH_CAST_ERROR';

export const TX_HASH_IN_PROGRESS_FALSE_SET = 'TX_HASH_IN_PROGRESS_FALSE_SET';

export const DISCONNECT_SET = 'DISCONNECT_SET';

export const CONTRACT_SIGN_IN_PROGRESS = 'CONTRACT_SIGN_IN_PROGRESS';
export const CONTRACT_SIGN_SUCCESS = 'CONTRACT_SIGN_SUCCESS';
export const CONTRACT_SIGN_ERROR = 'CONTRACT_SIGN_ERROR';
