export const MY_NFT_S_FETCH_IN_PROGRESS = 'MY_NFT_S_FETCH_IN_PROGRESS';
export const MY_NFT_S_FETCH_SUCCESS = 'MY_NFT_S_FETCH_SUCCESS';
export const MY_NFT_S_FETCH_ERROR = 'MY_NFT_S_FETCH_ERROR';

export const MY_NFT_S_INFO_FETCH_IN_PROGRESS = 'MY_NFT_S_INFO_FETCH_IN_PROGRESS';
export const MY_NFT_S_INFO_FETCH_SUCCESS = 'MY_NFT_S_INFO_FETCH_SUCCESS';
export const MY_NFT_S_INFO_FETCH_ERROR = 'MY_NFT_S_INFO_FETCH_ERROR';
